# Generated by Django 4.2.10 on 2024-03-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ishlab chiqaruvchi',
                'verbose_name_plural': 'Ishlab chiqaruvchilar',
            },
        ),
    ]
