# Generated by Django 4.2.10 on 2024-03-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Summa')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Boshqa daromad',
                'verbose_name_plural': 'Boshqa daromadlar',
            },
        ),
        migrations.CreateModel(
            name='SoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Sotilgan narx')),
                ('client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mijoz')),
                ('sold_date', models.DateField(blank=True, null=True, verbose_name='Sotilgan sana')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_products', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Sotilgan mahsulot',
                'verbose_name_plural': 'Sotilgan mahsulotlar',
            },
        ),
    ]
