# Generated by Django 5.0.1 on 2024-01-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bot_token', models.CharField(max_length=255, verbose_name='Bot token')),
                ('chat_id', models.CharField(max_length=255, verbose_name='Chat ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Is enabled')),
            ],
            options={
                'verbose_name': 'Telegram notification',
                'verbose_name_plural': 'Telegram notification',
            },
        ),
    ]
