# Generated by Django 4.2.10 on 2024-03-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_telegramnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramNotification',
        ),
    ]
